markdown: kramdown
baseurl: ''
exclude: ['README.md']
permalink: pretty

collections_dir: articles

collections:
  flappy_bird:
    sort_by: lesson
    output: true
    permalink: 'articles/flappy-bird/:title'
    featured: true
    excerpt: "In this tutorial series we work our way into rebuilding flappy bird"
    level: "beginner"